query GetUsers($name: String!) {
  search(query: $name, type: USER, first: 10) {
    edges {
      node {
        ... on User {
          id
          name
          bio
          url
        }
      }
    }
  }
}
