query GetIssues($name: String!) {
  search(query: $name, type: ISSUE, first: 50) {
    edges {
      node {
        ... on Issue {
          id
          url
          title
        }
      }
    }
  }
}
