query GetRepositories($name: String!) {
  search(query: $name, type: REPOSITORY, first: 100) {
    edges {
      node {
        ... on Repository {
          id
          name
          nameWithOwner
          description
          url
        }
      }
    }
  }
}
