query GetDiscussions($name: String!) {
  search(query: $name, type: DISCUSSION, first: 100) {
    edges {
      node {
        ... on Discussion {
          id
          url
          title
        }
      }
    }
  }
}
